### ISSUE TITLE
Script might have a bug

### ISSUE THREAD

**Issue by mjmabs** [darzanebor/mikroblack#7]
Great work on pulling together the data for a simple mikrotik script import but the following address are listed in the data and can cause a network to crash.

192.168.0.0/16 - This blacklist the entire private ipv4 subnet
224.0.0.0/3 - This breaks OSPF networking
172.16.0.0/12 - This is optional, but is the default ipv4 range for some VPN Tunnels

**Comment by darzanebor** [comment]
Thanks, noted and fixed in new lists.
